## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - gfortran
before_script: # homebrew for mac
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

# cache:
#     directories:
#      - /home/travis/.julia/v0.6/Cbc/deps/usr
#      - /home/travis/.julia/v0.6/Ipopt/deps/usr
#      - /home/travis/.julia/v0.7/Cbc/deps/usr
#      - /home/travis/.julia/v0.7/Ipopt/deps/usr

## uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.clone("https://github.com/jgoldfar/SPSBase.jl.git"); Pkg.build("SPSBase");'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SPSRunner"); Pkg.test("SPSRunner"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SPSRunner")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SPSRunner")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
