## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.4
  - nightly

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

sudo: false
cache:
  directories:
  - $HOME/usr

## uncomment and modify the following lines to manually install system packages
addons:
  apt: # apt-get for linux
    packages:
    - gfortran
env:
  - MAKEFLAGS="-j3"
    LD_LIBRARY_PATH=$HOME/usr/lib

# before_script: # homebrew for mac
#   - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
#   - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

script:
  - julia -e 'Pkg.clone("https://github.com/jgoldfar/SPSBase.jl.git"); Pkg.build("SPSBase");'
  - travis_wait 30 julia -e 'Pkg.clone(pwd())' > SPSRunner-clone.log 2>&1
  - travis_wait 20 julia -e 'Pkg.build("SPSRunner")' > SPSRunner-stdout.log 2>&1
  - gem install gist
  - gist SPSRunner-clone.log || echo empty
  - gist SPSRunner-stdout.log || echo empty
  - julia -e 'Pkg.test("SPSRunner"; coverage=true)'

before_cache:
  - cp -R $HOME/.julia/*/Cbc/deps/usr $HOME
  - cp -R $HOME/.julia/*/Ipopt/deps/usr $HOME
  - cp -R $HOME/.julia/*/CoinOptServices/deps/usr $HOME

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SPSRunner")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SPSRunner")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
